services:
  # list of services
  app:
    # name of service
    container_name: BlogServices
    build:
      context: . # build the docker file inside the current directory
      args:
        - DEV=true
    ports:
      - "8015:8015" # maps the port of current machine to the port of container
    volumes:
      - ./app:/app # this helps to reflect any changes in code to container (wirthout re-building)
      - blog-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8015"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - BASE_BACKEND_URL=${BASE_BACKEND_URL}
      - BASE_FRONTEND_URL=${BASE_FRONTEND_URL}
      # - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - SECURE_SSL_REDIRECT=0
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT =${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - EMAIL_SECRET_KEY=${EMAIL_SECRET_KEY}
      - DEBUG=1
    depends_on:
      - db

  db:
    container_name: BlogServices_DB
    image: postgres:16-alpine
    ports:
      - 5433:5432
    volumes:
      - blog-db-data:/var/lib/postgresql/data/blog
    environment:
      - PGDATA=/var/lib/postgresql/data/blog
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  blog-db-data:
  blog-static-data: