# Generated by Django 5.0.6 on 2024-05-27 07:39

import core.models.post_models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_activate', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.post_models.blog_category_image_file_path)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Archived', 'Archived')], default='Active', help_text='Indicates the status of the category', max_length=10)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('parentPostCategoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.postcategory')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SEOKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('keyword', models.CharField(max_length=255)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100, verbose_name='Post Title')),
                ('content', models.TextField(verbose_name='Post Content')),
                ('image', models.ImageField(upload_to=core.models.post_models.post_image_file_path, verbose_name='Post Image')),
                ('postStatus', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish'), ('archive', 'Archive')], default='draft', max_length=10, verbose_name='Post Status')),
                ('postPublishDate', models.DateTimeField(blank=True, null=True, verbose_name='Post Publish Date')),
                ('postArchivedDate', models.DateTimeField(blank=True, null=True, verbose_name='Post Archive Date')),
                ('isExternalSource', models.BooleanField(default=False, verbose_name='Is External Source')),
                ('externalLink', models.CharField(blank=True, max_length=255, null=True, verbose_name='External link')),
                ('commentsEnabled', models.BooleanField()),
                ('metaDescription', models.CharField(blank=True, help_text='\n        Stores a brief summary or description of the blog post,\n        typically used for SEO purposes and displayed in search engine results.\n        ', max_length=255, null=True, verbose_name='Meta Description')),
                ('readTime', models.IntegerField(help_text='\n        Estimates the time required to read the blog post\n        ', verbose_name='Estimated Read Time')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('relatedPosts', models.ManyToManyField(blank=True, to='core.post')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('postCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.postcategory', verbose_name='Post Category')),
                ('seoKeywords', models.ManyToManyField(to='core.seokeywords', verbose_name='SEO Keywords')),
                ('tags', models.ManyToManyField(to='core.tag', verbose_name='Post Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
