# Generated by Django 5.0.6 on 2024-06-22 16:05

import core.models.post_models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_activate', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('updatedDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date')),
                ('title', models.CharField(max_length=100, verbose_name='Post Title')),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=core.models.post_models.post_image_file_path, verbose_name='Post Image')),
                ('authorName', models.CharField(default='Unknown', max_length=100, verbose_name='Author Name')),
                ('postStatus', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish'), ('archive', 'Archive')], default='draft', max_length=10, verbose_name='Post Status')),
                ('postPublishDate', models.DateTimeField(blank=True, null=True, verbose_name='Post Publish Date')),
                ('postArchivedDate', models.DateTimeField(blank=True, null=True, verbose_name='Post Archive Date')),
                ('reviewStatus', models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('reject', 'Reject')], default='pending', max_length=10, verbose_name='Review Status')),
                ('reviewResponseDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Review Response Date')),
                ('isExternalSource', models.BooleanField(default=False, verbose_name='Is External Source')),
                ('externalLink', models.CharField(blank=True, max_length=255, null=True, verbose_name='External link')),
                ('commentsEnabled', models.BooleanField(default=True, verbose_name='Enable Comments')),
                ('metaDescription', models.CharField(blank=True, help_text='\n        Stores a brief summary or description of the blog post,\n        typically used for SEO purposes and displayed in search engine results.\n        ', max_length=255, null=True, verbose_name='Meta Description')),
                ('readTime', models.IntegerField(help_text='\n        Estimates the time required to read the blog post\n        ', verbose_name='Estimated Read Time')),
                ('excerpt', models.CharField(default='', help_text='\n        Provides a short summary or teaser of the blog post,\n        displayed on archive pages or in search results.\n        ', max_length=255, verbose_name='Excerpt')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('relatedPosts', models.ManyToManyField(blank=True, to='core.post')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('likeCount', models.PositiveIntegerField(blank=True, default=0, help_text='\n        Records the number of likes or thumbs-up the comment has received.\n        ', null=True)),
                ('disLikeCount', models.PositiveIntegerField(blank=True, default=0, help_text='\n        Records the number of dislikes or thumbs-down the comment has received.\n        ', null=True)),
                ('parentComment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='core.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('updatedDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='', upload_to=core.models.post_models.blog_category_image_file_path)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Archived', 'Archived')], default='Active', help_text='Indicates the status of the category', max_length=10)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parentPostCategoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.postcategory')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Post Category',
                'verbose_name_plural': 'Post Categories',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='postCategoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.postcategory', verbose_name='Post Category'),
        ),
        migrations.CreateModel(
            name='PostInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewCount', models.PositiveIntegerField(blank=True, default=0, help_text='\n        Tracks the number of views or visits the blog post has received.\n        ', null=True)),
                ('socialShareCount', models.PositiveIntegerField(blank=True, default=0, help_text='\n        Tracks the number of times the blog post has been shared\n        on social media platforms.\n        ', null=True)),
                ('ratingCount', models.PositiveIntegerField(blank=True, default=0, help_text='\n        Tracks the number of user ratings received for the blog post.\n        ', null=True)),
                ('averageRating', models.FloatField(blank=True, help_text='\n        Calculates the average rating score based on user ratings,\n        providing feedback on content quality.\n        ', null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('commentCount', models.IntegerField(blank=True, default=0, help_text='\n        Counts the number of comments posted on the blog post,\n        fostering community interaction and discussion.\n        ', null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postInformation', to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='SEOKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('updatedDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date')),
                ('keyword', models.CharField(max_length=255)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'SEO Keyword',
                'verbose_name_plural': 'SEO Keywords',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='seoKeywords',
            field=models.ManyToManyField(to='core.seokeywords', verbose_name='SEO Keywords'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('updatedDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date')),
                ('name', models.CharField(max_length=255)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='core.tag', verbose_name='Post Tags'),
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('disLike', 'DisLike')], max_length=7, verbose_name='Review Status')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PostRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(help_text='must be one of these: 1,2,3,4,5', validators=[django.core.validators.MaxValueValidator(5)])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
