# Generated by Django 5.0.6 on 2024-06-24 18:42

import core.models.post_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authorName',
            field=models.CharField(max_length=100, verbose_name='Author Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(help_text='\n        Provides a short summary or teaser of the blog post,\n        displayed on archive pages or in search results.\n        ', max_length=255, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=core.models.post_models.post_image_file_path, verbose_name='Post Image'),
        ),
    ]
