# Generated by Django 5.0.6 on 2024-06-01 05:50

import core.models.post_models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import djrichtextfield.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Post Category', 'verbose_name_plural': 'Post Categories'},
        ),
        migrations.AlterModelOptions(
            name='seokeywords',
            options={'verbose_name': 'SEO Keyword', 'verbose_name_plural': 'SEO Keywords'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='post',
            name='authorName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Author Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default=django.utils.timezone.now, help_text='\n        Provides a short summary or teaser of the blog post,\n        displayed on archive pages or in search results.\n        ', max_length=255, verbose_name='Excerpt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='reviewResponseDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Review Response Date'),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('reject', 'Reject')], default='pending', max_length=10, verbose_name='Review Status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='commentsEnabled',
            field=models.BooleanField(default=True, verbose_name='Enable Comments'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=djrichtextfield.models.RichTextField(verbose_name='Post Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updatedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=core.models.post_models.blog_category_image_file_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='updatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='updatedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='seokeywords',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='seokeywords',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='seokeywords',
            name='updatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='seokeywords',
            name='updatedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updatedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('likeCount', models.PositiveIntegerField(blank=True, default=0, help_text='\n        Records the number of likes or thumbs-up the comment has received.\n        ', null=True)),
                ('disLikeCount', models.PositiveIntegerField(blank=True, default=0, help_text='\n        Records the number of dislikes or thumbs-down the comment has received.\n        ', null=True)),
                ('parentComment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='core.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewCount', models.PositiveIntegerField(blank=True, default=0, help_text='\n        Tracks the number of views or visits the blog post has received.\n        ', null=True)),
                ('likeCount', models.PositiveIntegerField(blank=True, default=0, help_text='\n        Records the number of likes or thumbs-up the blog post has received.\n        ', null=True)),
                ('socialShareCount', models.PositiveIntegerField(blank=True, default=0, help_text='\n        Tracks the number of times the blog post has been shared\n        on social media platforms.\n        ', null=True)),
                ('ratingCount', models.PositiveIntegerField(blank=True, default=0, help_text='\n        Tracks the number of user ratings received for the blog post.\n        ', null=True)),
                ('averageRating', models.FloatField(blank=True, help_text='\n        Calculates the average rating score based on user ratings,\n        providing feedback on content quality.\n        ', null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('commentCount', models.IntegerField(blank=True, default=0, help_text='\n        Counts the number of comments posted on the blog post,\n        fostering community interaction and discussion.\n        ', null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(help_text='must be one of these: 1,2,3,4,5', validators=[django.core.validators.MaxValueValidator(5)])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('disLike', 'DisLike')], max_length=7, verbose_name='Review Status')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
