# Generated by Django 5.0.6 on 2024-05-22 08:04

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to=core.models.blog_category_image_file_path)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Archived', 'Archived')], default='Inactive', help_text='Indicates the status of the category', max_length=10)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='post_categories_created_by', to=settings.AUTH_USER_MODEL)),
                ('parentPostCategoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.postcategory')),
                ('updateddBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='post_categories_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
