# Generated by Django 5.0.6 on 2024-05-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_postcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='updateddBy',
            new_name='updatedBy',
        ),
    ]
