# Generated by Django 5.0.6 on 2024-06-01 06:31

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_options_alter_postcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(verbose_name='Post Content'),
        ),
    ]
