# Generated by Django 5.0.6 on 2024-07-10 06:48

import core.models.user_models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_authorname_alter_post_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='authorName',
        ),
        migrations.AddField(
            model_name='comment',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='comment',
            name='isDeleted',
            field=models.BooleanField(default=0, verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='tag',
            name='isDeleted',
            field=models.BooleanField(default=0, verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_models.user_image_file_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='reviewResponseDate',
            field=models.DateTimeField(null=True, verbose_name='Review Response Date'),
        ),
    ]
