# Generated by Django 5.0.6 on 2024-06-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authorName',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Author Name'),
        ),
    ]
