# Generated by Django 5.0.6 on 2024-07-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comment_options_remove_post_authorname_and_more'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS pg_trgm;"),
    ]
