# Generated by Django 5.0.6 on 2024-05-22 12:43

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_postcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.blog_category_image_file_path),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='updatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
