# Generated by Django 5.0.6 on 2024-07-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240720_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postinformation',
            options={'verbose_name': 'Post Information', 'verbose_name_plural': 'Posts Information'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_activate',
            new_name='is_activated',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_reset_password_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
