# Generated by Django 5.0.6 on 2024-05-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_postcategory_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Archived', 'Archived')], default='Active', help_text='Indicates the status of the category', max_length=10),
        ),
    ]
