# Generated by Django 5.0.6 on 2024-06-08 15:14

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(verbose_name='Post Content'),
        ),
    ]
