# Generated by Django 5.0.6 on 2024-06-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='relatedPosts',
            field=models.ManyToManyField(blank=True, null=True, to='core.post'),
        ),
    ]
