# Generated by Django 5.0.6 on 2024-06-11 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_relatedposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_post_relations', to='core.post')),
                ('to_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_post_relations', to='core.post')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='relatedPosts',
        ),
        migrations.AddField(
            model_name='post',
            name='relatedPosts',
            field=models.ManyToManyField(through='core.PostRelated', to='core.post'),
        ),
    ]
