# Generated by Django 5.0.6 on 2024-06-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_postrelated_alter_post_relatedposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postrelated',
            name='from_post',
        ),
        migrations.RemoveField(
            model_name='postrelated',
            name='to_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='relatedPosts',
        ),
        migrations.AddField(
            model_name='post',
            name='relatedPosts',
            field=models.ManyToManyField(blank=True, to='core.post'),
        ),
    ]
