# Generated by Django 5.0.6 on 2024-06-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_postrelated_from_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostRelated',
        ),
    ]
