# Generated by Django 5.0.6 on 2024-06-12 13:52

import core.models.post_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_postrelated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostDetail',
            new_name='PostAnalytics',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.post_models.post_image_file_path, verbose_name='Post Image'),
        ),
    ]
