# Generated by Django 5.0.6 on 2024-06-17 16:45

import core.models.post_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_postcategory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=core.models.post_models.blog_category_image_file_path),
            preserve_default=False,
        ),
    ]
