# Generated by Django 5.0.6 on 2024-06-19 06:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_postcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewCount', models.PositiveIntegerField(blank=True, default=0, help_text='\n        Tracks the number of views or visits the blog post has received.\n        ', null=True)),
                ('socialShareCount', models.PositiveIntegerField(blank=True, default=0, help_text='\n        Tracks the number of times the blog post has been shared\n        on social media platforms.\n        ', null=True)),
                ('ratingCount', models.PositiveIntegerField(blank=True, default=0, help_text='\n        Tracks the number of user ratings received for the blog post.\n        ', null=True)),
                ('averageRating', models.FloatField(blank=True, help_text='\n        Calculates the average rating score based on user ratings,\n        providing feedback on content quality.\n        ', null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('commentCount', models.IntegerField(blank=True, default=0, help_text='\n        Counts the number of comments posted on the blog post,\n        fostering community interaction and discussion.\n        ', null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
        ),
        migrations.DeleteModel(
            name='PostAnalytics',
        ),
    ]
