# Generated by Django 5.0.6 on 2024-06-19 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_postinformation_delete_postanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinformation',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postInformation', to='core.post'),
        ),
    ]
